apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: agent-stack-k8s-secrets
  namespace: buildkite
spec:
  secretStoreRef:
    name: nerc-secret-store #need to create
    kind: SecretStore
  target:
    name: agent-stack-k8s-secrets
  data:
  - secretKey: BUILDKITE_AGENT_TOKEN
    remoteRef:
      key: <REPLACE_IN_OVERLAY> #nerc/necr-ocp-test/agent-stack-k8s-secrets
      property: <REPLACE_IN_OVERLAY> #BUILDKITE_AGENT_TOKEN
  - secretKey: BUILDKITE_TOKEN
    remoteRef:
      key: <REPLACE_IN_OVERLAY> #nerc/necr-ocp-test/agent-stack-k8s-secrets
      property: <REPLACE_IN_OVERLAY> #BUILDKITE_TOKEN
