# Source: agent-stack-k8s/templates/deployment.yaml.tpl
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-stack-k8s
  namespace: buildkite
spec:
  selector:
    matchLabels:
      app: agent-stack-k8s
  template:
    metadata:
      labels:
        app: agent-stack-k8s
      annotations:
        checksum/config: 84c3b0a8f05fd7fe6259cd2859a7c70a25e221e09871747f4f3e8ac7bce85993
        checksum/secrets: 7f2c38e6b9d094cb0abcbae03e0706d16ec2a2575735810806a7a2922b45bc72
    spec:
      serviceAccountName: agent-stack-k8s-controller
      nodeSelector: {}
      tolerations: []
      containers:
        - name: controller
          terminationMessagePolicy: FallbackToLogsOnError
          image: ghcr.io/buildkite/agent-stack-k8s/controller:0.16.1@sha256:8abf162a9bda5fbce301a268b929c71f4267bfd87d49aab211ed94feeaaed89f
          env:
            - name: CONFIG
              value: /etc/config.yaml
          envFrom:
            - secretRef:
                name: agent-stack-k8s-secrets
          volumeMounts:
            - name: config
              mountPath: /etc/config.yaml
              subPath: config.yaml
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: config
          configMap:
            name: agent-stack-k8s-config
